discourse_reach_and_rights:
  discourse_reach_and_rights_enabled:
    default: false
    client: true
  discourse_reach_and_rights_debug_enabled:
    default: false
    client: true
  discourse_reach_and_rights_default_view:
    default: "table"
    type: enum
    client: true
    choices:
      - table
      - classic
      - short
  discourse_reach_and_rights_color_create:
    default: "#3498db"
    client: true
  discourse_reach_and_rights_color_reply:
    default: "#2ecc71"
    client: true
  discourse_reach_and_rights_color_see:
    default: "#f1c40f"
    client: true
  discourse_reach_and_rights_min_trust_level:
    default: 0
    client: true
  discourse_reach_and_rights_cache_ttl_minutes:
    default: 30
    client: false
